// The Tools super-hub catalog: 8 categories, 121 utilities.
// `id` values in IMPLEMENTED below open a real mini-app; everything else is
// catalogued UI that reports "coming soon" instead of crashing.
//
// Scope note: electric-scooter, drone and A5-sticker/printer tooling was
// removed in the hub refactor — this business no longer covers them. Vending
// covers drinks machines only (no bubblegum/capsule machines).

export const TOOL_CATEGORIES = [
  {
    key: "vending",
    label: "מכונות שתייה וטרנזיט",
    emoji: "🥤",
    color: "#10B981",
    tools: [
      { id: "vending-roi", name: "החזר השקעה למכונה", emoji: "📈" },
      { id: "can-profit", name: "רווח לפחית", emoji: "💰" },
      { id: "restock-planner", name: "מתכנן מילוי מלאי", emoji: "📦" },
      { id: "machine-uptime", name: "מעקב תקינות מכונה", emoji: "🩺" },
      { id: "coin-float", name: "עודף ומטבעות במכונה", emoji: "🪙" },
      { id: "cooling-cost", name: "עלות קירור וחשמל", emoji: "❄️" },
      { id: "expiry-track", name: "מעקב תפוגה", emoji: "📅" },
      { id: "location-score", name: "ניקוד מיקום למכונה", emoji: "📍" },
      { id: "transit-time", name: "זמן נסיעה בין מכונות", emoji: "🚌" },
      { id: "transit-cost", name: "עלות נסיעות שבועית", emoji: "🎫" },
      { id: "transit-load", name: "מחשבון עומס טרנזיט", emoji: "🚚" },
      { id: "route-planner", name: "מסלול סבב מכונות", emoji: "🗺️" },
      { id: "best-sellers", name: "המשקאות הנמכרים", emoji: "🏆" },
      { id: "price-tuning", name: "כיוונון מחירים", emoji: "🎚️" },
      { id: "supplier-compare", name: "השוואת ספקים", emoji: "⚖️" },
      { id: "machine-log", name: "יומן תקלות וטיפולים", emoji: "🛠️" },
    ],
  },
  {
    key: "dev",
    label: "פיתוח קוד ובינה מלאכותית",
    emoji: "💻",
    color: "#7C3AED",
    tools: [
      { id: "rn-ui-gen", name: "מחולל עיצוב RN", emoji: "🎨" },
      { id: "json-validator", name: "בודק JSON", emoji: "🧩" },
      { id: "regex-tester", name: "בודק Regex", emoji: "🔎" },
      { id: "base64", name: "Base64 קידוד/פענוח", emoji: "🔡" },
      { id: "uuid-gen", name: "מחולל UUID", emoji: "🆔" },
      { id: "hex-color", name: "בורר צבעים HEX", emoji: "🌈" },
      { id: "flex-playground", name: "מגרש Flexbox", emoji: "📐" },
      { id: "expo-doctor", name: "צ׳קליסט Expo", emoji: "🩻" },
      { id: "token-counter", name: "ספירת טוקנים", emoji: "🔢" },
      { id: "api-tester", name: "בודק API", emoji: "🛰️" },
      { id: "jwt-decode", name: "פענוח JWT", emoji: "🎫" },
      { id: "diff-text", name: "השוואת קוד", emoji: "🔀" },
      { id: "model-compare", name: "השוואת מודלים", emoji: "🤖" },
      { id: "cost-per-call", name: "עלות קריאת AI", emoji: "💸" },
      { id: "error-decoder", name: "מפענח שגיאות", emoji: "🚨" },
    ],
  },
  {
    key: "video",
    label: "עריכת וידאו ומושן",
    emoji: "🎬",
    color: "#EF4444",
    tools: [
      { id: "video-size", name: "מחשבון גודל וידאו", emoji: "💾" },
      { id: "fps-slowmo", name: "מחשבון סלו-מושן", emoji: "🎞️" },
      { id: "aspect-ratio", name: "יחסי מסך", emoji: "🖼️" },
      { id: "bitrate-calc", name: "מחשבון Bitrate", emoji: "📶" },
      { id: "render-time", name: "הערכת זמן רינדור", emoji: "⏳" },
      { id: "export-preset", name: "פריסטים לייצוא", emoji: "📤" },
      { id: "shot-list", name: "רשימת שוטים", emoji: "📋" },
      { id: "audio-sync", name: "סנכרון אודיו", emoji: "🎙️" },
      { id: "transition-ideas", name: "רעיונות למעברים", emoji: "✨" },
      { id: "color-lut", name: "מדריך LUT וצבע", emoji: "🎨" },
      { id: "subtitle-timing", name: "תזמון כתוביות", emoji: "💬" },
      { id: "reel-length", name: "אורך ריל אידיאלי", emoji: "📱" },
      { id: "hook-writer", name: "כתיבת הוק לפתיחה", emoji: "🪝" },
      { id: "music-bpm", name: "התאמת BPM לחיתוך", emoji: "🎵" },
      { id: "storage-plan", name: "תכנון אחסון פרויקט", emoji: "🗄️" },
    ],
  },
  {
    key: "import",
    label: "ייבוא ואליאקספרס",
    emoji: "📦",
    color: "#D4820A",
    tools: [
      { id: "ali-import", name: "מחשבון ייבוא אליאקספרס", emoji: "🛒" },
      { id: "customs-calc", name: "מחשבון מכס ומיסים", emoji: "🏛️" },
      { id: "usd-ils", name: "המרת דולר לשקל", emoji: "💱" },
      { id: "shipping-compare", name: "השוואת שיטות משלוח", emoji: "🚢" },
      { id: "delivery-eta", name: "זמן הגעה משוער", emoji: "📅" },
      { id: "supplier-rating", name: "ניקוד ספק", emoji: "⭐" },
      { id: "moq-calc", name: "כמות מינימלית להזמנה", emoji: "🔢" },
      { id: "bulk-discount", name: "מחשבון הנחת כמות", emoji: "🏷️" },
      { id: "product-research", name: "מחקר מוצר", emoji: "🔬" },
      { id: "competitor-price", name: "מחירי מתחרים", emoji: "👀" },
      { id: "listing-writer", name: "כתיבת תיאור מוצר", emoji: "✍️" },
      { id: "return-rate", name: "חישוב אחוז החזרות", emoji: "↩️" },
      { id: "package-size", name: "מידות ומשקל חבילה", emoji: "📏" },
      { id: "tracking-log", name: "מעקב משלוחים", emoji: "📍" },
      { id: "profit-per-unit", name: "רווח ליחידה", emoji: "💵" },
    ],
  },
  {
    key: "school",
    label: "שגרת פנימייה ולימודים",
    emoji: "🎓",
    color: "#5B3FA8",
    tools: [
      { id: "zmanim-routine", name: "זמני היום ושגרה", emoji: "🕯️" },
      { id: "seder-timer", name: "טיימר סדר", emoji: "⏲️" },
      { id: "chavruta-planner", name: "מתכנן חברותא", emoji: "👥" },
      { id: "daf-tracker", name: "מעקב דף יומי", emoji: "📖" },
      { id: "test-countdown", name: "ספירה למבחן", emoji: "📝" },
      { id: "study-split", name: "חלוקת חומר ללמידה", emoji: "🪓" },
      { id: "memorize-drill", name: "תרגול שינון", emoji: "🧠" },
      { id: "weekly-schedule", name: "מערכת שבועית", emoji: "🗓️" },
      { id: "laundry-turn", name: "תור כביסה", emoji: "🧺" },
      { id: "room-checklist", name: "צ׳קליסט חדר", emoji: "🛏️" },
      { id: "shabbat-prep", name: "הכנות לשבת", emoji: "🕍" },
      { id: "trip-home", name: "תכנון נסיעה הביתה", emoji: "🏠" },
      { id: "pocket-money", name: "ניהול דמי כיס", emoji: "🪙" },
      { id: "sleep-calc", name: "מחשבון שינה", emoji: "😴" },
      { id: "focus-log", name: "יומן פוקוס", emoji: "🎯" },
    ],
  },
  {
    key: "finance",
    label: "פיננסים מהירים",
    emoji: "💰",
    color: "#1B7F5C",
    tools: [
      { id: "vat-calc", name: "מע״מ והנחה אקספרס", emoji: "🧾" },
      { id: "margin-calc", name: "מחשבון רווחיות", emoji: "📈" },
      { id: "discount-calc", name: "מחשבון הנחות", emoji: "🏷️" },
      { id: "tip-split", name: "חלוקת חשבון", emoji: "🍽️" },
      { id: "savings-goal", name: "יעד חיסכון", emoji: "🎯" },
      { id: "cashflow", name: "תזרים חודשי", emoji: "🌊" },
      { id: "breakeven", name: "נקודת איזון", emoji: "⚖️" },
      { id: "tax-set-aside", name: "הפרשה למס", emoji: "🏛️" },
      { id: "loan-calc", name: "מחשבון הלוואה", emoji: "🏦" },
      { id: "debt-tracker", name: "מעקב חובות", emoji: "📕" },
      { id: "roi-calc", name: "מחשבון ROI", emoji: "💹" },
      { id: "invoice-gen", name: "מחולל חשבוניות", emoji: "📑" },
      { id: "expense-split", name: "מפצל הוצאות חדר", emoji: "🛏️" },
      { id: "price-history", name: "היסטוריית מחירים", emoji: "📉" },
      { id: "hourly-rate", name: "חישוב תעריף שעתי", emoji: "⏱️" },
    ],
  },
  {
    key: "prompts",
    label: "פרומפטים",
    emoji: "🪄",
    color: "#B05AC4",
    tools: [
      { id: "prompt-library", name: "ספריית פרומפטים", emoji: "📚" },
      { id: "prompt-builder", name: "מחולל פרומפטים AI", emoji: "🧱" },
      { id: "system-prompt", name: "תבנית System Prompt", emoji: "⚙️" },
      { id: "product-desc-prompt", name: "פרומפט תיאור מוצר", emoji: "🛍️" },
      { id: "video-script", name: "פרומפט תסריט וידאו", emoji: "🎬" },
      { id: "code-review-prompt", name: "פרומפט ביקורת קוד", emoji: "🔍" },
      { id: "summarize-prompt", name: "פרומפט סיכום", emoji: "📄" },
      { id: "translate-prompt", name: "פרומפט תרגום", emoji: "🌐" },
      { id: "image-prompt", name: "פרומפט לתמונה", emoji: "🖼️" },
      { id: "hebrew-tone", name: "כיוונון סגנון עברי", emoji: "🇮🇱" },
      { id: "few-shot", name: "בונה דוגמאות Few-Shot", emoji: "🎯" },
      { id: "chain-thought", name: "תבנית שרשור חשיבה", emoji: "🔗" },
      { id: "prompt-tester", name: "בודק פרומפטים", emoji: "🧪" },
      { id: "negative-prompt", name: "פרומפט שלילי", emoji: "🚫" },
      { id: "prompt-history", name: "היסטוריית פרומפטים", emoji: "🕰️" },
    ],
  },
  {
    key: "utils",
    label: "כלי עזר",
    emoji: "🧰",
    color: "#4B5563",
    tools: [
      { id: "qr-gen", name: "מחולל ברקודים/QR", emoji: "🔳" },
      { id: "unit-conv", name: "המרת יחידות", emoji: "📐" },
      { id: "percent-calc", name: "מחשבון אחוזים", emoji: "％" },
      { id: "random-picker", name: "בוחר אקראי", emoji: "🎲" },
      { id: "password-gen", name: "מחולל סיסמאות", emoji: "🔑" },
      { id: "text-counter", name: "ספירת מילים ותווים", emoji: "🔢" },
      { id: "case-convert", name: "המרת Case", emoji: "🔠" },
      { id: "timestamp-conv", name: "המרת Timestamp", emoji: "🕰️" },
      { id: "countdown", name: "ספירה לאחור", emoji: "⏲️" },
      { id: "world-clock", name: "שעון עולמי", emoji: "🌍" },
      { id: "hebrew-date", name: "ממיר תאריך עברי", emoji: "📆" },
      { id: "ruler", name: "סרגל מסך", emoji: "📏" },
      { id: "noise-meter", name: "מד רעש", emoji: "🔊" },
      { id: "emoji-picker", name: "בורר אימוג׳י", emoji: "😀" },
      { id: "notes-quick", name: "פתק מהיר", emoji: "🗒️" },
    ],
  },
];

// Tool ids that open a real mini-app.
export const IMPLEMENTED = new Set([
  "vending-roi",
  "video-size",
  "rn-ui-gen",
  "ali-import",
  "zmanim-routine",
  "json-validator",
  "qr-gen",
  // Phase 2 batch
  "transit-load",
  "prompt-builder",
  "fps-slowmo",
  "expense-split",
  "vat-calc",
]);

// Flat list for search + counting.
export const ALL_TOOLS = TOOL_CATEGORIES.flatMap((cat) =>
  cat.tools.map((t) => ({ ...t, categoryKey: cat.key, categoryLabel: cat.label, color: cat.color }))
);

export const TOOL_COUNT = ALL_TOOLS.length;

export const toolById = (id) => ALL_TOOLS.find((t) => t.id === id) || null;
