// The Tools super-hub catalog: 8 categories × 15 tools = 120 utilities.
// `id` values marked in IMPLEMENTED below open a real mini-app; everything
// else is catalogued UI that reports "coming soon" instead of crashing.

export const TOOL_CATEGORIES = [
  {
    key: "logistics",
    label: "לוגיסטיקה ורכבים",
    emoji: "🛴",
    color: "#2E6BE6",
    tools: [
      { id: "scooter-range", name: "מחשבון טווח קורקינט", emoji: "🔋" },
      { id: "delivery-eta", name: "חישוב זמן הגעה", emoji: "⏱️" },
      { id: "route-order", name: "סידור סבב משלוחים", emoji: "🗺️" },
      { id: "fuel-cost", name: "עלות דלק לנסיעה", emoji: "⛽" },
      { id: "km-price", name: "תמחור לפי ק״מ", emoji: "📏" },
      { id: "tire-psi", name: "לחץ אוויר מומלץ", emoji: "🛞" },
      { id: "battery-health", name: "בריאות סוללה", emoji: "🔌" },
      { id: "charge-time", name: "זמן טעינה משוער", emoji: "⚡" },
      { id: "load-limit", name: "משקל מטען מותר", emoji: "⚖️" },
      { id: "delivery-log", name: "יומן משלוחים", emoji: "📒" },
      { id: "parking-timer", name: "טיימר חניה", emoji: "🅿️" },
      { id: "service-due", name: "תזכורת טיפול", emoji: "🔧" },
      { id: "insurance-doc", name: "מסמכי ביטוח", emoji: "📄" },
      { id: "weather-ride", name: "תנאי נסיעה", emoji: "🌦️" },
      { id: "theft-checklist", name: "צ׳קליסט נעילה", emoji: "🔐" },
    ],
  },
  {
    key: "print",
    label: "מעבדת הדפסות",
    emoji: "🖨️",
    color: "#B05AC4",
    tools: [
      { id: "a5-margins", name: "מחשבון שוליים A5", emoji: "📐" },
      { id: "paper-sizes", name: "טבלת גדלי נייר", emoji: "📃" },
      { id: "dpi-calc", name: "מחשבון DPI", emoji: "🔍" },
      { id: "ink-cost", name: "עלות דיו לעמוד", emoji: "🩸" },
      { id: "bleed-calc", name: "חישוב בליד וחיתוך", emoji: "✂️" },
      { id: "sticker-yield", name: "כמה מדבקות מגיליון", emoji: "🏷️" },
      { id: "cmyk-rgb", name: "המרת CMYK/RGB", emoji: "🎨" },
      { id: "laminate-calc", name: "חישוב למינציה", emoji: "🧴" },
      { id: "print-quote", name: "הצעת מחיר הדפסה", emoji: "🧾" },
      { id: "font-preview", name: "תצוגת גופנים", emoji: "🔤" },
      { id: "imposition", name: "סידור עמודים בגיליון", emoji: "🗂️" },
      { id: "gsm-guide", name: "מדריך משקל נייר", emoji: "📚" },
      { id: "binding-calc", name: "חישוב כריכה", emoji: "📓" },
      { id: "batch-rename", name: "שינוי שם קבצים", emoji: "🔁" },
      { id: "print-queue", name: "תור עבודות", emoji: "📋" },
    ],
  },
  {
    key: "drinks",
    label: "מכונות משקאות",
    emoji: "🥤",
    color: "#1E9E58",
    tools: [
      { id: "co2-level", name: "מד גז CO₂", emoji: "🫧" },
      { id: "syrup-ratio", name: "יחס סירופ למים", emoji: "🧪" },
      { id: "cup-stock", name: "מלאי כוסות", emoji: "🥤" },
      { id: "machine-clean", name: "לוח ניקוי מכונה", emoji: "🧽" },
      { id: "temp-check", name: "בדיקת טמפרטורה", emoji: "🌡️" },
      { id: "profit-per-cup", name: "רווח לכוס", emoji: "💰" },
      { id: "refill-alert", name: "התראת מילוי", emoji: "🔔" },
      { id: "ice-usage", name: "צריכת קרח", emoji: "🧊" },
      { id: "flavor-mix", name: "מחשבון תערובת טעמים", emoji: "🍹" },
      { id: "machine-log", name: "יומן תקלות", emoji: "🛠️" },
      { id: "supplier-order", name: "הזמנה מספק", emoji: "🚚" },
      { id: "expiry-track", name: "מעקב תפוגה", emoji: "📅" },
      { id: "sales-per-machine", name: "מכירות לפי מכונה", emoji: "📊" },
      { id: "energy-cost", name: "עלות חשמל למכונה", emoji: "🔌" },
      { id: "cup-size-calc", name: "המרת גדלי כוסות", emoji: "📏" },
    ],
  },
  {
    key: "code",
    label: "פיתוח וקוד",
    emoji: "💻",
    color: "#003366",
    tools: [
      { id: "json-validator", name: "בודק JSON", emoji: "🧩" },
      { id: "base64", name: "Base64 קידוד/פענוח", emoji: "🔡" },
      { id: "url-encode", name: "URL Encode", emoji: "🔗" },
      { id: "regex-tester", name: "בודק Regex", emoji: "🔎" },
      { id: "uuid-gen", name: "מחולל UUID", emoji: "🆔" },
      { id: "hash-gen", name: "מחולל Hash", emoji: "#️⃣" },
      { id: "color-picker", name: "בורר צבעים HEX", emoji: "🎨" },
      { id: "cron-parser", name: "מפענח Cron", emoji: "⏰" },
      { id: "diff-text", name: "השוואת טקסטים", emoji: "🔀" },
      { id: "minify", name: "כיווץ קוד", emoji: "🗜️" },
      { id: "timestamp-conv", name: "המרת Timestamp", emoji: "🕰️" },
      { id: "jwt-decode", name: "פענוח JWT", emoji: "🎫" },
      { id: "case-convert", name: "המרת Case", emoji: "🔠" },
      { id: "lorem-gen", name: "מחולל טקסט מדומה", emoji: "📝" },
      { id: "api-tester", name: "בודק API", emoji: "🛰️" },
    ],
  },
  {
    key: "video",
    label: "וידאו ורחפנים",
    emoji: "🎬",
    color: "#E14848",
    tools: [
      { id: "drone-battery", name: "זמן טיסה לסוללה", emoji: "🚁" },
      { id: "video-size", name: "חישוב גודל קובץ", emoji: "💾" },
      { id: "fps-calc", name: "מחשבון FPS וסלואו", emoji: "🎞️" },
      { id: "aspect-ratio", name: "יחסי מסך", emoji: "🖼️" },
      { id: "bitrate-calc", name: "מחשבון Bitrate", emoji: "📶" },
      { id: "shot-list", name: "רשימת שוטים", emoji: "📋" },
      { id: "golden-hour", name: "שעת הזהב", emoji: "🌅" },
      { id: "storage-plan", name: "תכנון אחסון", emoji: "🗄️" },
      { id: "nd-filter", name: "בחירת פילטר ND", emoji: "🕶️" },
      { id: "export-preset", name: "פריסטים לייצוא", emoji: "📤" },
      { id: "render-time", name: "הערכת זמן רינדור", emoji: "⏳" },
      { id: "audio-sync", name: "סנכרון אודיו", emoji: "🎙️" },
      { id: "flight-log", name: "יומן טיסות", emoji: "🗒️" },
      { id: "no-fly", name: "אזורי איסור טיסה", emoji: "🚫" },
      { id: "client-quote-video", name: "הצעת מחיר צילום", emoji: "💵" },
    ],
  },
  {
    key: "time",
    label: "ניהול זמן",
    emoji: "⏳",
    color: "#D4AF37",
    tools: [
      { id: "zmanim", name: "שעון זמני היום", emoji: "🕯️" },
      { id: "pomodoro", name: "טיימר פומודורו", emoji: "🍅" },
      { id: "shift-calc", name: "מחשבון שעות עבודה", emoji: "🧮" },
      { id: "week-planner", name: "מתכנן שבועי", emoji: "🗓️" },
      { id: "hebrew-date", name: "ממיר תאריך עברי", emoji: "📆" },
      { id: "countdown", name: "ספירה לאחור", emoji: "⏲️" },
      { id: "world-clock", name: "שעון עולמי", emoji: "🌍" },
      { id: "break-reminder", name: "תזכורת הפסקה", emoji: "☕" },
      { id: "task-split", name: "מפרק משימות", emoji: "🪓" },
      { id: "focus-log", name: "יומן פוקוס", emoji: "🎯" },
      { id: "meeting-cost", name: "עלות פגישה", emoji: "💸" },
      { id: "deadline-track", name: "מעקב דדליינים", emoji: "🚩" },
      { id: "habit-chain", name: "שרשרת הרגלים", emoji: "🔥" },
      { id: "sleep-calc", name: "מחשבון שינה", emoji: "😴" },
      { id: "time-zone-conv", name: "המרת אזורי זמן", emoji: "🕐" },
    ],
  },
  {
    key: "finance",
    label: "פיננסים",
    emoji: "💰",
    color: "#1B7F5C",
    tools: [
      { id: "vat-calc", name: "מחשבון מע״מ", emoji: "🧾" },
      { id: "margin-calc", name: "מחשבון רווחיות", emoji: "📈" },
      { id: "discount-calc", name: "מחשבון הנחות", emoji: "🏷️" },
      { id: "loan-calc", name: "מחשבון הלוואה", emoji: "🏦" },
      { id: "currency-conv", name: "המרת מטבע", emoji: "💱" },
      { id: "tip-split", name: "חלוקת חשבון", emoji: "🍽️" },
      { id: "savings-goal", name: "יעד חיסכון", emoji: "🎯" },
      { id: "cashflow", name: "תזרים חודשי", emoji: "🌊" },
      { id: "invoice-gen", name: "מחולל חשבוניות", emoji: "📑" },
      { id: "expense-split", name: "פיצול הוצאות", emoji: "➗" },
      { id: "breakeven", name: "נקודת איזון", emoji: "⚖️" },
      { id: "tax-set-aside", name: "הפרשה למס", emoji: "🏛️" },
      { id: "price-history", name: "היסטוריית מחירים", emoji: "📉" },
      { id: "debt-tracker", name: "מעקב חובות", emoji: "📕" },
      { id: "roi-calc", name: "מחשבון ROI", emoji: "💹" },
    ],
  },
  {
    key: "utils",
    label: "Utilities",
    emoji: "🧰",
    color: "#5A6470",
    tools: [
      { id: "qr-gen", name: "מחולל ברקודים/QR", emoji: "🔳" },
      { id: "unit-conv", name: "המרת יחידות", emoji: "📐" },
      { id: "percent-calc", name: "מחשבון אחוזים", emoji: "％" },
      { id: "random-picker", name: "בוחר אקראי", emoji: "🎲" },
      { id: "password-gen", name: "מחולל סיסמאות", emoji: "🔑" },
      { id: "text-counter", name: "ספירת מילים ותווים", emoji: "🔢" },
      { id: "clipboard-history", name: "היסטוריית העתקות", emoji: "📋" },
      { id: "flashlight", name: "פנס", emoji: "🔦" },
      { id: "ruler", name: "סרגל מסך", emoji: "📏" },
      { id: "level", name: "פלס דיגיטלי", emoji: "🧭" },
      { id: "noise-meter", name: "מד רעש", emoji: "🔊" },
      { id: "battery-info", name: "מידע סוללה", emoji: "🔋" },
      { id: "wifi-qr", name: "QR לרשת WiFi", emoji: "📶" },
      { id: "emoji-picker", name: "בורר אימוג׳י", emoji: "😀" },
      { id: "notes-quick", name: "פתק מהיר", emoji: "🗒️" },
    ],
  },
];

// Tool ids that open a real mini-app.
export const IMPLEMENTED = new Set([
  "a5-margins",
  "scooter-range",
  "json-validator",
  "zmanim",
  "qr-gen",
]);

// Flat list for search + counting.
export const ALL_TOOLS = TOOL_CATEGORIES.flatMap((cat) =>
  cat.tools.map((t) => ({ ...t, categoryKey: cat.key, categoryLabel: cat.label, color: cat.color }))
);

export const TOOL_COUNT = ALL_TOOLS.length;
